[project]
name = "hexlet-code"
version = "0.1.0"
description = "Analizador de páginas"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "flask",
    "gunicorn",
    "psycopg2-binary>=2.9.12",
    "python-dotenv",
    "requests>=2.34.2",
    "validators>=0.35.0",
]

[tool.setuptools]
packages = ["page_analyzer"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
