[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Analizador de páginas"
authors = ["Jacobo Jaramillo Uribe <jacobo.jaramillo@hotmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12"
flask = "^2.3"
python-dotenv = "^1.0"
gunicorn = "^21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"